name: Events are in action for testing

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches:
      - 'master'


jobs:
  build:

    runs-on: ubuntu-latest
    steps:
        - name: Step1
          run: echo "Hello World in step1"
        - name: Step2
          run: echo "Hello World in step2"
        - name: Step3
          run: echo "Hello World in step3"
