name: Events are in action

on:
 # push:
 #   branches: [ "dev" ]
  pull_request:
    branches:
      - 'master'


jobs:
  build:

    runs-on: ubuntu-latest
    steps:
        - name: Hello Step
          run: echo "Hello World"
