name: Manual trigger
run-name: Deploy in master by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Who to greet for day"
        default: "World"

jobs:
    hello:
        runs-on: ubuntu-latest

        steps:
        - name: Hello Step
          run: echo "Hello ${{ github.event.inputs.name }}"
